### ISSUE TITLE
Mypy issues with BaseSettings and SettingsConfigDict - v2

### ISSUE THREAD

**Issue by axeng** [pydantic/pydantic-settings#95]
It seems that mypy has some issues with the new BaseSettings.
I did the same tests with pydantic v1 and it did not throw these errors.

Using this example:
```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class TestSettings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env")

    test_field: str

settings = TestSettings()
```

Mypy is throwing the following:
```shell
test.py:4: error: Incompatible types (expression has type "str", TypedDict item "env_file" has type "Path | list[Path] | tuple[Path, ...] | None")  [typeddict-item]
test.py:8: error: Missing named argument "test_field" for "TestSettings"  [call-arg]
Found 2 errors in 1 file (checked 1 source file)
```

Here the Mypy configuration I am using:
```toml
[tool.mypy]
ignore_missing_imports = true
plugins = [
    "pydantic.mypy",
]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true
warn_unreachable = true
```

----------

`pydantic` version: 2.0
`pydantic-core` version: 2.0.1
`pydantic-settings` version: 2.0
`mypy` version: 1.4.1

Selected Assignee: @dmontagu
